name: differnt hellos

on:
    workflow_dispatch:

jobs:
    say-hello-inline-bash:
        runs-on: ubuntu-24.04
        steps:
            - run: echo "hello world from bash"

    say-hello-inline-python:
        runs-on: ubuntu-24.04
        steps:
            - run: print("hello from python")
              shell: python
    

    say-hello-actions:
        runs-on: ubuntu-24.04
        steps:
            - uses: actions/hello-world-javascript-action@e76147da8e5c81eaf017dede5645551d4b94427b
              with: 
                who-to-greets: "from actions hello"